# Generated by Django 5.1.1 on 2024-10-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=69)),
                ('USN', models.CharField(max_length=69)),
                ('email', models.CharField(max_length=69)),
                ('collegename', models.CharField(max_length=69)),
                ('offer_statsu', models.CharField(max_length=69)),
                ('start_date', models.CharField(max_length=69)),
                ('end_date', models.CharField(max_length=69)),
                ('project_report', models.CharField(max_length=69)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
